# Generated by Django 4.2.6 on 2024-06-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_productsfeatures_productsstores_feature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsfeatures',
            options={'verbose_name_plural': 'Product Features'},
        ),
        migrations.AddField(
            model_name='productsorder',
            name='Customer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Customer Name'),
        ),
    ]
