# Generated by Django 4.2.6 on 2024-06-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_productsfeatures_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
    ]
