# Generated by Django 4.2.6 on 2024-06-10 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_myuser_is_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceName', models.CharField(max_length=100, verbose_name='Service Name')),
                ('ServiceImage', models.ImageField(blank=True, null=True, upload_to='media/Images/', verbose_name='Service Image')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'OurServices',
            },
        ),
    ]
