# Generated by Django 4.2.6 on 2024-06-10 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_ourservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeoplesCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100, verbose_name='Category Name')),
                ('CategoryImage', models.ImageField(blank=True, null=True, upload_to='media/Images/', verbose_name='Category Image')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Peoples Categories',
            },
        ),
        migrations.AddField(
            model_name='productscategories',
            name='Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.peoplescategories', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='productsstores',
            name='Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.peoplescategories', verbose_name='Type'),
        ),
    ]
