# Generated by Django 4.2.6 on 2024-06-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_peoplescategories_productscategories_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsstores',
            name='InitialPrice',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Initial Product price'),
        ),
        migrations.AlterField(
            model_name='productsstores',
            name='InitialProductQuantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Initial Product Quantity*'),
        ),
        migrations.AlterField(
            model_name='productsstores',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Main Price*'),
        ),
    ]
